packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^5.3.0
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.12.2
  '@types/node': ^24.4.0
  '@unocss/reset': ^66.5.1
  '@vueuse/core': ^13.9.0
  bumpp: ^10.2.3
  eslint: ^9.35.0
  floating-vue: ^5.2.2
  lint-staged: ^16.1.6
  pinia: ^3.0.3
  pnpm: ^10.16.1
  simple-git-hooks: ^2.13.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.5.1
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.21
