packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^5.4.1
  '@antfu/ni': ^26.0.1
  '@antfu/utils': ^9.2.1
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.13.0
  '@types/node': ^24.5.2
  '@unocss/reset': ^66.5.2
  '@vueuse/core': ^13.9.0
  bumpp: ^10.2.3
  eslint: ^9.36.0
  floating-vue: ^5.2.2
  lint-staged: ^16.2.0
  pinia: ^3.0.3
  pnpm: ^10.17.1
  simple-git-hooks: ^2.13.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.5.2
  unplugin-vue-components: ^29.1.0
  vite: ^7.1.7
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.21
