shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^7.0.1
  '@antfu/ni': ^28.2.0
  '@antfu/utils': ^9.3.0
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.21.0
  '@types/node': ^25.0.9
  '@unocss/reset': ^66.6.0
  '@vueuse/core': ^14.1.0
  '@yunyoujun/docs': ^0.1.14
  bumpp: ^10.4.0
  eslint: ^9.39.2
  floating-vue: ^5.2.2
  lint-staged: ^16.2.7
  pinia: ^3.0.4
  pnpm: ^10.28.0
  simple-git-hooks: ^2.13.1
  tsx: ^4.21.0
  typedoc: ^0.28.16
  typedoc-plugin-markdown: ^4.9.0
  typedoc-vitepress-theme: ^1.1.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.6.0
  unplugin-vue-components: ^31.0.0
  vite: ^7.3.1
  vite-plugin-vue-devtools: ^8.0.5
  vite-tsconfig-paths: ^6.0.4
  vitepress: ^2.0.0-alpha.15
  vitepress-plugin-group-icons: ^1.6.9
  vitest: ^4.0.17
  vue: ^3.5.26
